# Generated by Django 5.2.6 on 2026-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rol',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor')], default='ALUMNO', max_length=20),
        ),
        migrations.AddField(
            model_name='profesor',
            name='rol',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor')], default='ALUMNO', max_length=20),
        ),
    ]
