# Generated by Django 5.2.6 on 2025-12-31 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_Evaluable',
            fields=[
                ('nombre_tarea', models.CharField(max_length=200)),
                ('tipo_tarea', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('EVALUABLE', 'Evaluable')], max_length=20)),
                ('es_evaluable', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('id_tarea_evaluable', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('profesores', models.ManyToManyField(to='usuarios.profesor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea_Grupal',
            fields=[
                ('nombre_tarea', models.CharField(max_length=200)),
                ('tipo_tarea', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('EVALUABLE', 'Evaluable')], max_length=20)),
                ('es_evaluable', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('id_tarea_grupal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea_Individual',
            fields=[
                ('nombre_tarea', models.CharField(max_length=200)),
                ('tipo_tarea', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal'), ('EVALUABLE', 'Evaluable')], max_length=20)),
                ('es_evaluable', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('id_tarea_individual', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
