# Generated by Django 5.2.6 on 2026-01-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_delete_profesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
        ),
    ]
