# Generated by Django 5.2.6 on 2026-01-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tarea_evaluable_tarea_grupal_tarea_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='DNI',
            new_name='dni',
        ),
    ]
