# Generated by Django 5.2.6 on 2026-01-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alumno_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarea_Evaluable',
        ),
    ]
