# Generated by Django 5.2.6 on 2026-01-06 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_delete_tarea_evaluable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea_Evaluable_Grupal',
            fields=[
                ('id_tarea_evaluable', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('id_tarea_grupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tarea_grupal')),
                ('profesores', models.ManyToManyField(to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea_Evaluable_Individual',
            fields=[
                ('id_tarea_evaluable', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('id_tarea_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tarea_individual')),
                ('profesores', models.ManyToManyField(to='usuarios.usuario')),
            ],
        ),
    ]
