# Generated by Django 5.2.6 on 2026-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tarea_evaluable_grupal_tarea_evaluable_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea_evaluable_individual',
            name='id_tarea_individual',
        ),
        migrations.RemoveField(
            model_name='tarea_evaluable_individual',
            name='profesores',
        ),
        migrations.AddField(
            model_name='tarea_grupal',
            name='profesores',
            field=models.ManyToManyField(related_name='tarea_grupal_evaluable', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='tarea_individual',
            name='profesores',
            field=models.ManyToManyField(related_name='tarea_individual_evaluable', to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Tarea_Evaluable_Grupal',
        ),
        migrations.DeleteModel(
            name='Tarea_Evaluable_Individual',
        ),
    ]
