# Generated by Django 5.2.6 on 2026-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_tarea_evaluable_individual_id_tarea_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_grupal',
            name='es_evaluable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tarea_grupal',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas_grupales_profesores', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea_grupal',
            name='tipo_tarea',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='es_evaluable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, related_name='tarea_individual_profesores', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='tipo_tarea',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], max_length=20),
        ),
    ]
