# Generated by Django 5.2.6 on 2026-01-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_tarea_grupal_es_evaluable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea_grupal',
            name='alumno',
        ),
        migrations.AddField(
            model_name='tarea_grupal',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas_grupales_alumnos', to='usuarios.usuario'),
        ),
    ]
