# Generated by Django 5.2.6 on 2026-01-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_tarea_grupal_alumno_tarea_grupal_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_grupal',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas_grupales_alumnos', to='usuarios.alumno'),
        ),
        migrations.AlterField(
            model_name='tarea_grupal',
            name='profesores',
            field=models.ManyToManyField(blank=True, null=True, related_name='tareas_grupales_profesores', to='usuarios.profesor'),
        ),
    ]
