# Generated by Django 5.2.6 on 2026-01-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_tarea_grupal_alumnos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_grupal',
            name='tipo_tarea',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], default='GRUPAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='tipo_tarea',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], default='INDIVIDUAL', max_length=20),
        ),
    ]
