# Generated by Django 5.2.6 on 2026-01-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_tarea_grupal_tipo_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea_grupal',
            name='alumno_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='tarea_individual',
            name='alumno_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
        migrations.AlterField(
            model_name='tarea_grupal',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='tareas_grupales_alumnos', to='usuarios.alumno'),
        ),
        migrations.AlterField(
            model_name='tarea_grupal',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='tareas_grupales_profesores', to='usuarios.profesor'),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='tarea_individual_profesores', to='usuarios.usuario'),
        ),
    ]
