# Generated by Django 5.2.6 on 2026-01-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_tarea_grupal_alumno_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea_grupal',
            name='alumno_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
        migrations.AlterField(
            model_name='tarea_individual',
            name='alumno_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
    ]
